# Generated by Django 5.1 on 2024-08-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patent",
            name="document_url",
        ),
        migrations.AddField(
            model_name="patent",
            name="document",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="patent_documents/"
            ),
        ),
    ]
